// This file was generated by WTL subclass control wizard 
// LogListBox.h : Declaration of the CLogListBox

#ifndef LOGLISTBOX_H
#define LOGLISTBOX_H

#pragma once

#include <atlbase.h>
#include <atlctrls.h>
#include <atlmisc.h>
#include <atlcrack.h>
#include "../InputBox.h"

// CLogListBox

namespace ImageEditor {

class InputBoxControl :
	public CWindowImpl<InputBoxControl, CEdit,CControlWinTraits>, public InputBox
{
	public:
		typedef CWindowImpl<InputBoxControl, CEdit,CControlWinTraits> Base;
		InputBoxControl();
		~InputBoxControl();
		DECLARE_WND_SUPERCLASS(_T("CInputBoxControl"), CEdit::GetWndClassName())
		
		 BEGIN_MSG_MAP(CLogListBox)
			MSG_WM_KILLFOCUS(OnKillFocus)
			MESSAGE_HANDLER(WM_DESTROY, OnDestroy)
			MESSAGE_HANDLER(WM_KEYUP, OnKeyUp )
		 END_MSG_MAP()

		 // Handler prototypes:
		 //  LRESULT MessageHandler(UINT uMsg, WPARAM wParam, LPARAM lParam, BOOL& bHandled);
		 //  LRESULT CommandHandler(WORD wNotifyCode, WORD wID, HWND hWndCtl, BOOL& bHandled);
		 //  LRESULT NotifyHandler(int idCtrl, LPNMHDR pnmh, BOOL& bHandled);
		LRESULT OnDestroy(UINT uMsg, WPARAM wParam, LPARAM lParam,BOOL& bHandled);
		LRESULT OnKillFocus(HWND hwndNewFocus);
		LRESULT OnKeyUp(UINT uMsg, WPARAM wParam, LPARAM lParam, BOOL& bHandled);
	public:
		int NotifyParent(int nItem);
		BOOL SubclassWindow(HWND hWnd);
};

}

#endif // LOGLISTBOX_H


