// This file was generated by WTL Dialog wizard 
// ServerSelectDlg.h : Declaration of the CServerSelectDlg

#pragma once

#include "atlheaders.h"
#include "resource.h"       // main symbols
#include <atlframe.h>
#include <atlcrack.h>
// CServerSelectDlg

class CServerSelectDlg : 
public
	CWindowImpl<CServerSelectDlg, CListViewCtrl>, public CMessageFilter
	//public CListViewCtrl
	//public CDialogResize<CServerSelectDlg>	
{
public:
	CServerSelectDlg();
	~CServerSelectDlg();
	enum { IDD = IDD_SERVERSELECTDLG };

	DECLARE_WND_SUPERCLASS(_T("CServerSelectDlg"), CListViewCtrl::GetWndClassName())

    BEGIN_MSG_MAP(CServerSelectDlg)
		MESSAGE_HANDLER(WM_INITDIALOG, OnInitDialog)
		//MESSAGE_HANDLER(WM_ACTIVATE, OnActivate)
		MESSAGE_HANDLER(WM_MOUSEACTIVATE, OnMouseActivate)
		MSG_WM_SHOWWINDOW(OnShowWindow)

        COMMAND_HANDLER(IDOK, BN_CLICKED, OnClickedOK)
        COMMAND_HANDLER(IDCANCEL, BN_CLICKED, OnClickedCancel)
//		  CHAIN_MSG_MAP(CListViewCtrl);
//		CHAIN_MSG_MAP(CDialogResize<CServerSelectDlg>)
    END_MSG_MAP()
	 virtual BOOL PreTranslateMessage(MSG* pMsg);

	//BEGIN_DLGRESIZE_MAP(CServerSelectDlg)
	//END_DLGRESIZE_MAP()
    // Handler prototypes:
    //  LRESULT MessageHandler(UINT uMsg, WPARAM wParam, LPARAM lParam, BOOL& bHandled);
    //  LRESULT CommandHandler(WORD wNotifyCode, WORD wID, HWND hWndCtl, BOOL& bHandled);
    //  LRESULT NotifyHandler(int idCtrl, LPNMHDR pnmh, BOOL& bHandled);
	LRESULT OnInitDialog(UINT uMsg, WPARAM wParam, LPARAM lParam, BOOL& bHandled);
	LRESULT OnClickedOK(WORD wNotifyCode, WORD wID, HWND hWndCtl, BOOL& bHandled);
	LRESULT OnClickedCancel(WORD wNotifyCode, WORD wID, HWND hWndCtl, BOOL& bHandled);
	LRESULT OnActivate(UINT uMsg, WPARAM wParam, LPARAM lParam, BOOL& bHandled);
LRESULT OnMouseActivate(UINT uMsg, WPARAM wParam, LPARAM lParam, BOOL& bHandled);

LRESULT OnShowWindow(BOOL fShow, UINT status);
	bool ShowPopup(HWND hwndOwner);
	bool m_done;
};


