// This file was generated by WTL Dialog wizard 
// TextViewDlg.h : Declaration of the CTextViewDlg

#pragma once

#include "../../resource.h"       // main symbols
#include <atlframe.h>
#include <atlmisc.h>
#include "../../Func/LangClass.h"
// CTextViewDlg
using namespace WTL;
class CTextViewDlg : 
	public CDialogImpl<CTextViewDlg>,
	public CDialogResize<CTextViewDlg>	
{
public:
	CTextViewDlg(const CString &text, const CString &title, const CString &info, const CString &question , const CString &okCaption=TR("OK"),const CString &cancelCaption=TR("Отмена"));
	~CTextViewDlg();
	enum { IDD = IDD_TEXTVIEWDLG };

    BEGIN_MSG_MAP(CTextViewDlg)
		MESSAGE_HANDLER(WM_INITDIALOG, OnInitDialog)
        COMMAND_HANDLER(IDOK, BN_CLICKED, OnClickedOK)
        COMMAND_HANDLER(IDCANCEL, BN_CLICKED, OnClickedCancel)
		CHAIN_MSG_MAP(CDialogResize<CTextViewDlg>)
    END_MSG_MAP()

	BEGIN_DLGRESIZE_MAP(CTextViewDlg)
			DLGRESIZE_CONTROL(IDC_QUESTIONLABEL, DLSZ_MOVE_Y|DLSZ_SIZE_X)
		DLGRESIZE_CONTROL(IDC_TEXTEDIT, DLSZ_SIZE_X|DLSZ_SIZE_Y)
		DLGRESIZE_CONTROL(IDOK, DLSZ_MOVE_X| DLSZ_MOVE_Y)
	
		DLGRESIZE_CONTROL(IDCANCEL, DLSZ_MOVE_X|DLSZ_MOVE_Y)
	
	END_DLGRESIZE_MAP()
    // Handler prototypes:
    //  LRESULT MessageHandler(UINT uMsg, WPARAM wParam, LPARAM lParam, BOOL& bHandled);
    //  LRESULT CommandHandler(WORD wNotifyCode, WORD wID, HWND hWndCtl, BOOL& bHandled);
    //  LRESULT NotifyHandler(int idCtrl, LPNMHDR pnmh, BOOL& bHandled);
	LRESULT OnInitDialog(UINT uMsg, WPARAM wParam, LPARAM lParam, BOOL& bHandled);
	LRESULT OnClickedOK(WORD wNotifyCode, WORD wID, HWND hWndCtl, BOOL& bHandled);
	LRESULT OnClickedCancel(WORD wNotifyCode, WORD wID, HWND hWndCtl, BOOL& bHandled);
	CString m_okCaption,m_cancelCaption, m_text, m_title, m_info, m_question;
};


