// This file was generated by WTL Dialog wizard 
// Declaration of the CAddFtpServerDialog

#pragma once

#include "resource.h"       // main symbols
// CAddFtpServerDialog

class CAddFtpServerDialog : 
	public CDialogImpl<CAddFtpServerDialog>	
{
public:
	CAddFtpServerDialog();
	~CAddFtpServerDialog();
	enum { IDD = IDD_ADDFTPSERVERDIALOG };

    BEGIN_MSG_MAP(CAddFtpServerDialog)
		MESSAGE_HANDLER(WM_INITDIALOG, OnInitDialog)
        COMMAND_HANDLER(IDOK, BN_CLICKED, OnClickedOK)
        COMMAND_HANDLER(IDCANCEL, BN_CLICKED, OnClickedCancel)
		NOTIFY_HANDLER(IDC_CONNECTIONNAMEEDIT, EN_CHANGE, OnConnectionNameEditChange);
		NOTIFY_HANDLER(IDC_SERVEREDIT, EN_CHANGE, OnServerEditChange);
		NOTIFY_HANDLER(IDC_REMOTEDIRECTORYEDIT, EN_CHANGE, OnRemoteDireetoryEditChange);
		NOTIFY_HANDLER(IDC_DOWNLOADURLEDIT, EN_CHANGE, OnDownloadUrlEditChange);

	
	END_MSG_MAP()
    // Handler prototypes:
    //  LRESULT MessageHandler(UINT uMsg, WPARAM wParam, LPARAM lParam, BOOL& bHandled);
    //  LRESULT CommandHandler(WORD wNotifyCode, WORD wID, HWND hWndCtl, BOOL& bHandled);
    //  LRESULT NotifyHandler(int idCtrl, LPNMHDR pnmh, BOOL& bHandled);
	LRESULT OnInitDialog(UINT uMsg, WPARAM wParam, LPARAM lParam, BOOL& bHandled);
	LRESULT OnClickedOK(WORD wNotifyCode, WORD wID, HWND hWndCtl, BOOL& bHandled);
	LRESULT OnClickedCancel(WORD wNotifyCode, WORD wID, HWND hWndCtl, BOOL& bHandled);
	LRESULT OnConnectionNameEditChange(int idCtrl, LPNMHDR pnmh, BOOL& bHandled);
	LRESULT OnServerEditChange(int idCtrl, LPNMHDR pnmh, BOOL& bHandled);
	LRESULT OnRemoteDireetoryEditChange(int idCtrl, LPNMHDR pnmh, BOOL& bHandled);
	LRESULT OnDownloadUrlEditChange(int idCtrl, LPNMHDR pnmh, BOOL& bHandled);
};


