// ExplorerIntegration.idl : IDL source for ExplorerIntegration
//

// This file will be processed by the MIDL tool to
// produce the type library (ExplorerIntegration.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	object,
    uuid(B0DA607F-C6C4-4545-B0E2-C2408DC8C08A),
	dual,
	nonextensible,
	helpstring("IIShellContextMenu Interface"),
	pointer_default(unique)
]
interface IIShellContextMenu : IDispatch{
};
[
	uuid(95453956-224E-4996-9224-20829C6F0AAD),
	version(1.0),
	helpstring("ExplorerIntegration 1.0 Type Library")
]
library ExplorerIntegrationLib
{
	importlib("stdole2.tlb");
	[
		uuid(4B4E72F9-F01C-422E-BF65-98D12861743C),
		helpstring("IShellContextMenu Class")
	]
	coclass IShellContextMenu
	{
		[default] interface IIShellContextMenu;
	};
};
