// IUCom.idl : IDL source for IUCom
//

// This file will be processed by the MIDL tool to
// produce the type library (IUCom.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(665BA35B-B689-4D5D-8D90-80D16B410124),
	dual,
	nonextensible,
	helpstring("ISendToShlExt Interface"),
	pointer_default(unique)
]
interface ISendToShlExt : IDispatch{
};
[
	uuid(A5AC392C-4CD2-4494-9B45-0A50A4308FDE),
	version(1.0),
	helpstring("IUCom 1.0 Type Library")
]
library IUComLib
{
	importlib("stdole2.tlb");
	[
		uuid(535E39BD-5883-454C-AFFC-C54B66B18206),
		helpstring("SendToShlExt Class")
	]
	coclass SendToShlExt
	{
		[default] interface ISendToShlExt;
	};
};
