//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Image Uploader.rc
//
#define IDR_RT_MANIFEST1                1
#define IDC_STOP                        2
#define IDC_FILEINFOLABEL               2
#define IDD_ABOUTBOX                    100
#define IDD_VIDEOGRABBER                103
#define IDD_UPLOADDLG                   104
#define IDD_SCREENSHOTDLG               105
#define IDD_VIDEOGRABBERPARARAMS        106
#define IDD_LOGOSETTINGS                107
#define IDD_WIZARDDLG                   108
#define IDD_WELCOMEDLG                  109
#define IDD_UPLOADSETTINGS              110
#define IDD_IMAGEVIEW                   111
#define IDD_SIZEEXCEED                  115
#define IDD_STATUSDLG                   117
#define IDD_LOGWINDOW                   118
#define IDD_HOTKEYEDITOR                119
#define IDD_FOLDERSELECT                120
#define IDD_SERVERFOLDERSELECT          120
#define IDD_NEWFOLDERDLG                122
#define IDD_SERVERPARAMSDLG             124
#define IDD_TEXTVIEWDLG                 125
#define IDD_UPDATEDLG                   126
#define IDD_ADDFTPSERVERDIALOG          127
#define IDR_MAINFRAME                   128
#define IDD_MAINDLG                     129
#define IDD_LOGINDLG                    130
#define IDD_LANGSELECT                  131
#define IDD_MEDIAINFODLG                132
#define IDD_SETTINGSDLG                 133
#define IDD_GENERALSETTINGS             134
#define IDD_UPLOADSETTINGSPAGE          135
#define IDD_RESULTSPANEL                136
#define IDD_TRAYSETTINGSPAGE            137
#define IDD_HOTKEYSETTINGSPAGE          138
#define IDD_SCREENSHOTSETTINGSPAGE      139
#define IDD_IMAGEDOWNLOADER             141
#define IDD_RESULTSWINDOW               142
#define IDD_CONVERTPRESETDLG            143
#define IDD_THUMBSETTINGSPAGE           144
#define IDD_HISTORYWINDOW               145
#define IDD_THUMBEDITOR                 146
#define IDD_INPUTDIALOG                 147
#define IDD_IMAGEREUPLOADER             148
#define IDD_SHORTENURL                  149
#define IDD_ADDDIRECTORYSERVERDLG       150
#define IDR_CONTEXTMENU                 202
#define IDI_GRAB                        207
#define IDI_IMAGES                      209
#define IDB_BITMAP1                     214
#define IDB_BITMAP2                     216
#define IDI_ICONSETTINGS                217
#define IDI_ICONFOLDER                  218
#define IDI_ICONINFO                    219
#define IDI_ICON1                       220
#define IDI_ICONREGION                  220
#define IDR_CONTEXTMENU2                222
#define IDI_CLIPBOARD                   223
#define IDR_PNG1                        224
#define IDR_PNG2                        225
#define IDB_BITMAP3                     227
#define IDB_BITMAP4                     228
#define IDR_REGISTRY1                   229
#define IDI_ERRORICON                   230
#define IDI_ICONWARNING                 231
#define IDI_ADDITIONAL                  232
#define IDI_CLOSE                       233
#define IDI_WINDOW                      234
#define IDR_PROGRESSGIF                 241
#define IDB_BITMAP6                     242
#define IDB_SERVERTOOLBARBMP2           242
#define IDB_ICONUNDOPNG                 242
#define IDI_ICONWINDOWS                 245
#define IDI_FREEFORM                    246
#define IDI_ICONADD                     248
#define IDI_ICONADDFOLDER               249
#define IDI_ICONWEB                     250
#define IDI_ICON2                       251
#define IDI_ICONEDIT                    251
#define IDI_ICONWHITEPAGE               252
#define IDI_ICONSAVE                    253
#define IDI_ICONHISTORY                 254
#define IDI_ICON3                       255
#define IDI_ICONDELETE                  255
#define IDI_ICONRELOAD                  258
#define IDB_PNG1                        259
#define IDI_ICON4                       260
#define IDI_ICONLINK                    260
#define IDD_QUICKSETUPDLG               261
#define IDD_INTEGRATIONSETTINGS         262
#define IDI_ICONADDITEM                 263
#define IDI_ICON6                       264
#define IDI_ICONDELETEITEM              264
#define IDD_SERVERSELECTORCONTROL       265
#define IDI_ICONUSER                    266
#define IDD_GENERALSETTINGS1            266
#define IDD_DEFAULTSERVERSSETTINGS      267
#define IDI_ICON5                       267
#define IDI_ICONFOLDER2                 267
#define IDD_UPLOADPARAMSDLG             268
#define IDI_ICONUP                      268
#define IDI_ICONSETTINGS2               269
#define IDD_CONTEXTMENUITEMDLG          269
#define IDD_TEXTPARAMSWINDOW            270
#define IDI_ICON7                       271
#define IDI_ICONDOWN                    271
#define IDD_CLEARHISTORYDLG             271
#define IDB_PNG2                        272
#define IDB_PNG3                        273
#define IDB_DROPDOWNICONPNG             273
#define IDB_TOO                         274
#define IDB_TOOLMOVEICONPNG             274
#define IDB_TOOLCROPPING                275
#define IDB_ICONTOOLPENCIL              276
#define IDB_ICONTOOLBRUSHPNG            277
#define IDB_ICONTOOLTEXTPNG             278
#define IDB_ICONTOOLFILLEDRECTANGLE     279
#define IDB_ICONCOLORPICKERPNG          281
#define IDB_ICONTOOLLINE                282
#define IDB_PNG4                        283
#define IDB_ICONTOOLRECTANGLEPNG        283
#define IDB_ICONTOOLSELECTION           284
#define IDB_PNG5                        286
#define IDB_ICONTOOLARROWPNG            286
#define IDB_ICONTOOLBLURINGRECTANGLEPNG 287
#define IDC_CURSOR1                     288
#define IDC_COLORPICKERCURSOR           288
#define IDB_ICONTOOLROUNDEDRECTANGLE    289
#define IDB_ICONTOOLFILLEDROUNDEDRECTANGLE 290
#define IDB_ICONTOOLELLIPSE             291
#define IDB_PNG7                        292
#define IDB_ICONTOOLFILLEDELLIPSE       292
#define IDB_PNG6                        293
#define IDB_ICONTOOLMARKER              293
#define IDB_ICONSAVEPNG                 294
#define IDB_ICONADDPNG                  295
#define IDB_PNG8                        296
#define IDB_ICONUPLOADPNG               296
#define IDI_ICONBOLD                    298
#define IDI_ICON9                       299
#define IDI_ICONITALIC                  299
#define IDI_ICONUNDERLINE               300
#define IDB_PNG9                        302
#define IDR_ICONMAINNEW                 302
#define IDB_ICONCLIPBOARDPNG            303
#define IDI_ICON8                       305
#define IDI_ICON_MAIN_OLD               305
#define IDI_ICONTRAYACTIVE              307
#define IDI_ICON_HELP_DROPDOWN          308
#define IDC_ADDIMAGES                   1000
#define IDC_ADDVIDEO                    1001
#define IDC_LIST1                       1002
#define IDC_FILELIST                    1002
#define IDC_LISTBOX                     1002
#define IDC_THUMBLIST                   1002
#define IDC_MSGLIST                     1002
#define IDC_COMMANDBOX                  1002
#define IDC_HOTKEYLIST                  1002
#define IDC_PARAMLIST                   1002
#define IDC_UPDATELISTVIEW              1002
#define IDC_CONTEXTMENUITEMS            1002
#define IDC_CONTEXTMENUITEMSLIST        1002
#define IDC_UPLOADTABLE                 1002
#define IDC_KEEPASIS                    1003
#define IDC_KEEPPROPORTIONS             1004
#define IDC_IMAGEWIDTH                  1005
#define IDC_IMAGEHEIGHT                 1006
#define IDC_YOURLOGO                    1007
#define IDC_YOURTEXT                    1008
#define IDC_RESIZE                      1009
#define IDC_RESIZEBYWIDTH               1009
#define IDC_XLABEL                      1010
#define IDC_FORMATLIST                  1011
#define IDC_QUALITYSPIN                 1012
#define IDC_FORMATLABEL                 1013
#define IDC_QUALITYLABEL                1014
#define IDC_QUALITYEDIT                 1015
#define IDC_PERCENTLABEL                1016
#define IDC_APPLY                       1017
#define IDC_THUMBFORMATLABEL            1017
#define IDC_LOGOOPTIONS                 1018
#define IDC_ENABLEPREVIEW               1019
#define IDC_THUMBFORMATLIST             1019
#define IDC_FRAME                       1020
#define IDC_THUMBQUALITYLABEL           1020
#define IDC_PREVIEW                     1021
#define IDC_THUMBQUALITYEDIT            1021
#define IDC_IMAGEPARAMETERS             1022
#define IDC_CHECK7                      1023
#define IDC_THUMBQUALITYSPIN            1023
#define IDC_USESERVERTHUMBNAILS         1024
#define IDC_COMBO1                      1025
#define IDC_LOGOPOSITION                1025
#define IDC_CODETYPE                    1025
#define IDC_LANGLIST                    1025
#define IDC_LEFTBUTTONDOUBLECLICKCOMBO  1025
#define IDC_ACCESSTYPECOMBO             1025
#define IDC_PERCENTLABEL2               1025
#define IDC_SERVERLIST                  1026
#define IDC_LEFTBUTTONCLICKCOMBO        1026
#define IDC_COMBO2                      1026
#define IDC_FONTSIZECOMBO               1026
#define IDC_CHECK4                      1027
#define IDC_TEXTPOSITION                1027
#define IDC_SAVEPROPORTIONS             1027
#define IDC_STARTUPLOADINGFROMSHELL     1027
#define IDC_MIDDLEBUTTONCLICKCOMBO      1027
#define IDC_USEOLDREGIONSCREENSHOTMETHOD 1027
#define IDC_ADDFILESIZE                 1028
#define IDC_RIGHTBUTTONCLICKCOMBO       1028
#define IDC_SAVEPROPORTIONS2            1028
#define IDC_EDIT4                       1029
#define IDC_PROXYLOGINEDIT              1029
#define IDC_SERVERLIST2                 1029
#define IDC_THUMBWIDTH                  1030
#define IDC_NUMOFFRAMESEDIT             1031
#define IDC_EXPAND                      1032
#define IDC_BUTTON5                     1033
#define IDC_THUMBTEXTCOLOR              1033
#define IDC_WIDTHLABEL                  1034
#define IDC_THUMBTEXTCOLOR2             1034
#define IDC_SERVERCONFIG                1035
#define IDC_DEINTERLACE                 1036
#define IDC_DRAWFRAME                   1036
#define IDC_TEXTOVERTHUMB               1036
#define IDC_USETEMPLATE                 1036
#define IDC_USEIECOOKIES                1036
#define IDC_USEAVIINFO                  1036
#define IDC_SHELLIMGCONTEXTMENUITEM     1036
#define IDC_AUTOCOPYTOCLIPBOARD         1036
#define IDC_SHELLINTEGRATION            1036
#define IDC_SHOWTRAYICON                1036
#define IDC_WINDOWBUTTONCHECKBOX        1036
#define IDC_DOAUTH                      1036
#define IDC_CREATETHUMBNAILS            1037
#define IDC_PROGRESSBAR                 1038
#define IDC_TEXTOVERTHUMB2              1038
#define IDC_GRAB                        1039
#define IDC_EDIT1                       1040
#define IDC_FILEEDIT                    1040
#define IDC_COLUMNSEDIT                 1040
#define IDC_LOGOEDIT                    1040
#define IDC_THUMBSPERPAGE               1040
#define IDC_THUMBSPERLINE               1040
#define IDC_LOGINEDIT                   1040
#define IDC_FILEINFOEDIT                1040
#define IDC_IMAGEEDITORPATH             1040
#define IDC_FILERETRYLIMIT              1040
#define IDC_FOLDERTITLEEDIT             1040
#define IDC_TEXTEDIT                    1040
#define IDC_UPDATEINFO                  1040
#define IDC_SCREENSHOTFILENAMEEDIT      1040
#define IDC_FRAMEWIDTH                  1040
#define IDC_WIDTHEDIT                   1040
#define IDC_SOURCEURLEDIT               1040
#define IDC_CONNECTIONNAMEEDIT          1040
#define IDC_MEMO                        1040
#define IDC_MENUITEMTITLEEDIT           1040
#define IDC_SELECTVIDEO                 1041
#define IDC_STROKECOLOR                 1041
#define IDC_LOGINBUTTON                 1041
#define IDC_REGIONSELECT                1041
#define IDC_FORALL                      1041
#define IDC_BROWSEBUTTON                1041
#define IDC_ACTIONRETRYLIMIT            1041
#define IDC_EDITHOTKEY                  1041
#define IDC_MEDIAINFOFONT               1041
#define IDC_NEWFOLDERBUTTON             1041
#define IDC_SCREENSHOTFOLDEREDIT        1041
#define IDC_HEIGHTEDIT                  1041
#define IDC_FILEINFOEDIT2               1041
#define IDC_INPUTEDIT                   1041
#define IDC_SERVEREDIT                  1041
#define IDC_DONE                        1042
#define IDC_LOGINBUTTON2                1042
#define IDC_VIDEOSNAPSHOTSFOLDEREDIT    1042
#define IDC_LOGINEDITBOX                1042
#define IDC_RADIO1                      1043
#define IDC_MULTIPLEFILES               1043
#define IDC_SOURCECODERADIO             1043
#define IDC_PASSWORDEDITBOX             1043
#define IDC_ALLTIMERADIO                1043
#define IDC_RADIO2                      1044
#define IDC_SAVEASONE                   1044
#define IDC_HEIGHTRADIO                 1044
#define IDC_LINKSLISTRADIO              1044
#define IDC_SCREENSHOTFILENAMEEDIT2     1044
#define IDC_SNAPSHOTFILENAMEEDIT        1044
#define IDC_REMOTEDIRECTORYEDIT         1044
#define IDC_EDIT2                       1045
#define IDC_TRANSPARENCY                1045
#define IDC_QUALITY                     1045
#define IDC_PASSWORDEDIT                1045
#define IDC_ADDRESSEDIT                 1045
#define IDC_THUMBTEXT                   1045
#define IDC_FOLDERDESCREDIT             1045
#define IDC_CONNECTIONNAMEEDIT6         1045
#define IDC_DOWNLOADURLEDIT             1045
#define IDC_GRABINFOLABEL               1046
#define IDC_BUTTON3                     1047
#define IDC_GRABBERPARAMS               1047
#define IDC_SELECTCOLOR                 1047
#define IDC_SERVERMENU                  1047
#define IDC_NEWTHUMBNAIL                1047
#define IDC_UPDOWN                      1048
#define IDC_PROGRESS1                   1049
#define IDC_UPLOADPROGRESS              1049
#define IDC_DOWNLOADFILESPROGRESS       1049
#define IDC_INFOUPLOAD                  1050
#define IDC_CODEEDIT                    1051
#define IDC_CANCEL2                     1057
#define IDC_SCREENSHOT                  1058
#define IDI_SCREENSHOT                  1058
#define IDC_DELAYSPIN                   1059
#define IDI_DROPDOWN                    1059
#define IDC_DELAYEDIT                   1060
#define IDC_ENTIRESCREEN                1061
#define IDC_WINDOWHIDINGDELAY           1061
#define IDC_ACTIVEWINDOW                1062
#define IDC_TILEWIDTH                   1063
#define IDC_GAPWIDTH                    1064
#define IDC_GAPHEIGHT                   1065
#define IDC_TRANSPIN                    1066
#define IDC_EDITYOURTEXT                1067
#define IDC_SELECTFONT                  1068
#define IDC_LOGOBROWSE                  1069
#define IDC_LOGOGROUP                   1070
#define IDC_COPYALL                     1071
#define IDC_SELECTBKCOLOR               1073
#define IDC_SELECTOPTION                1076
#define IDC_TITLE                       1077
#define IDC_PREV                        1078
#define IDC_NEXT                        1079
#define IDC_BUTTON2                     1080
#define IDC_PROPERTIES                  1080
#define IDC_FRAMECOLOR                  1080
#define IDC_FILEINFOBUTTON              1080
#define IDC_VIEWLOG                     1080
#define IDC_SHOWLOG                     1080
#define IDC_ABOUT                       1081
#define IDC_HELPBUTTON                  1082
#define IDC_SPIN1                       1083
#define IDC_THUMBPERLINESPIN            1083
#define IDC_THUMBWIDTHSPIN              1083
#define IDC_HEADBITMAP                  1084
#define IDC_SPEEDLABEL                  1085
#define IDC_LEFTLABEL                   1086
#define IDC_CUSTOM1                     1087
#define IDC_FRAMELABEL                  1088
#define IDC_DELETE                      1089
#define IDC_TEXTBACKGROUND              1091
#define IDC_COLOR2                      1091
#define IDC_THUMBFONT                   1092
#define IDC_COLOR1                      1093
#define IDC_IMAGEUPLOADERLABEL          1094
#define IDC_THANKSTOLABEL               1095
#define IDC_IMAGEUPLOADERLABEL2         1095
#define IDC_FILEPROGRESS                1096
#define IDC_PROGRESSLABEL               1098
#define IDC_COMMONPROGRESS              1099
#define IDC_COMMONPROGRESS2             1100
#define IDC_COMMONPERCENTS              1101
#define IDC_CURRENTFILELABEL            1102
#define IDC_LOGINFRAME                  1103
#define IDC_SOVET                       1104
#define IDC_SOVET2                      1105
#define IDC_WELCOMEMSG                  1106
#define IDC_EXTRACTFRAMES               1107
#define IDC_PATHTOFILELABEL             1108
#define IDC_SAVEAS                      1109
#define IDC_COLUMNSEDITLABEL            1110
#define IDC_PREVIEWWIDTHLABEL           1111
#define IDC_INTERVALHORLABEL            1112
#define IDC_INTERVALVERTLABEL           1113
#define IDC_APPEA                       1114
#define IDC_APPEARANCEGROUP             1114
#define IDC_DELAYLABEL                  1115
#define IDC_MAKESCREENLABEL             1116
#define IDC_DELAYLABEL2                 1116
#define IDC_SECLABEL                    1117
#define IDC_THUMBSETTINGS               1118
#define IDC_SECLABEL2                   1118
#define IDC_MSECLABEL                   1118
#define IDC_SELECTSERVERLABEL           1119
#define IDC_PRESSUPLOADBUTTON           1120
#define IDC_TEXTONIMAGEGROUP            1121
#define IDC_ENTERYOURTEXTLABEL          1122
#define IDC_TEXTCOLORLABEL              1123
#define IDC_TEXTSTROKECOLOR             1124
#define IDC_THUMBPARAMS                 1125
#define IDC_FILENAMELABEL               1126
#define IDC_LOGOPOSITIONLABEL           1127
#define IDC_TEXTPOSITIONLABEL           1128
#define IDC_FRAMECOLORLABEL             1129
#define IDC_THUMBTEXTCOLORLABEL         1130
#define IDC_GRADIENTCOLOR1LABEL         1131
#define IDC_GRADIENTCOLOR2LABEL         1132
#define IDC_IMAGESPERLINELABEL          1133
#define IDC_THUMBSTROKECOLOR            1133
#define IDC_THUMBSTROKECOLORLABEL       1133
#define IDC_CODETYPELABEL               1134
#define IDC_LINK1                       1135
#define IDC_LINK3                       1137
#define IDC_EMAIL                       1137
#define IDC_LOGINLABEL                  1138
#define IDC_PASSWORDLABEL               1139
#define IDC_PLEASECHOOSE                1140
#define IDC_CHECK2                      1142
#define IDC_USETHUMBTHUMBNAILS          1142
#define IDC_USETHUMBTEMPLATE            1142
#define IDC_NEEDSAUTH                   1142
#define IDC_AUTOSHOWLOG                 1142
#define IDC_ONEINSTANCE                 1142
#define IDC_MEDIAINFOONIMAGE            1142
#define IDC_REMOVECORNERS               1142
#define IDC_PXLABEL                     1143
#define IDC_TABCONTROL                  1144
#define IDC_LANGUAGELABEL               1145
#define IDC_PORTEDIT                    1146
#define IDC_SERVERTYPECOMBO             1147
#define IDC_PROXYPASSWORDEDIT           1148
#define IDC_USEPROXYSERVER              1149
#define IDC_ADDRESSLABEL                1150
#define IDC_PORTLABEL                   1151
#define IDC_SERVERTYPE                  1152
#define IDC_SHELLVIDEOCONTEXTMENUITEM   1153
#define SHELLVIDEOCONTEXTMENUITEM       1153
#define IDC_SHELLSENDTOITEM             1154
#define IDC_FILEEXCEEDNAME              1156
#define IDC_FILEEXCEEDSIZE2             1157
#define IDC_TEXT                        1158
#define IDC_WHATTODO                    1159
#define IDC_IMAGESETTINGS               1160
#define IDC_INTEGRATIONGROUP            1161
#define IDC_CONNECTIONSETTINGS          1162
#define IDC_CHANGESWILLBE               1163
#define IDC_GETINFOABOUTFILELABEL       1164
#define IDC_LEFTBITMAP                  1165
#define IDC_STATICLOGO                  1167
#define IDC_THANKSTOGROUP               1168
#define IDC_BETATESTERS                 1169
#define IDC_CONTACTEMAIL                1171
#define IDC_CMDBAR                      1172
#define IDC_TRANSLATERS                 1173
#define IDC_IMAGEEDITLABEL              1174
#define IDC_LOGGROUP                    1176
#define IDC_THUMBTEXTLABEL              1177
#define IDC_CONFIRMONEXIT               1178
#define IDC_GROUPPARAMS                 1179
#define IDC_IGNOREERRORS                1180
#define IDC_GROUPPARAMS2                1180
#define IDC_UPLOADERRORLABEL            1181
#define IDC_RETRIES1LABEL               1182
#define IDC_RETRIES2LABEL               1183
#define IDC_RESULTSTAB                  1184
#define IDC_CHECK3                      1185
#define IDC_CASCADEDCONTEXTMENU         1185
#define IDC_ADDSHADOW                   1185
#define IDC_DEVELOPERMODE               1185
#define IDC_LEFTBUTTONDOUBLECLICKLABEL  1186
#define IDC_LEFTBUTTONCLICKLABEL        1187
#define IDC_MIDDLEBUTTONCLICKLABEL      1188
#define IDC_RIGHTBUTTONCLICKLABEL       1189
#define IDC_MOUSEREACTIONGROUP          1190
#define IDC_LOCALHOTKEY                 1193
#define IDC_GLOBALHOTKEY                1194
#define IDC_LOCALHOTKEYLABEL            1195
#define IDC_GLOBALHOTKEYLABEL           1196
#define IDC_ATTENTION                   1197
#define IDC_TEXTCOLOR                   1199
#define IDC_FOLDERLISTLABEL             1200
#define IDC_FOLDERNAMELABEL             1201
#define IDC_FOLDERDESCRLABEL            1202
#define IDC_FOLDERLINK                  1203
#define IDC_ACCESSTYPELABEL             1204
#define IDC_FOLDERTREE                  1205
#define IDC_IMAGESERVERGROUPBOX         1206
#define IDC_FILESERVERGROUPBOX          1207
#define IDC_ANIMATIONSTATIC             1208
#define IDC_CURLINFOLABEL               1210
#define IDC_QUESTIONLABEL               1211
#define IDC_TITLETEXT                   1212
#define IDC_UPDATESLABEL                1213
#define IDC_SETTINGSPAGESLIST           1215
#define IDC_SITELINK                    1216
#define IDC_FOREGROUNDWHENSHOOTING      1217
#define IDC_DOCUMENTATION               1217
#define IDC_PARAMETERSHINTLABEL         1218
#define IDC_SCREENSHOTFILENAMELABEL     1220
#define IDC_SCREENSHOTFOLDERLABEL       1221
#define IDC_SCREENSHOTSFOLDERSELECT     1222
#define IDC_WATCHCLIPBOARD              1223
#define IDC_UPLOADBUFFERLABEL           1224
#define IDC_UPLOADBUFFERSIZEEDIT        1225
#define IDC_IMAGEDOWNLOADERTIP          1226
#define IDC_THREADSCOUNTLABEL           1226
#define IDC_MAXTHREADSLABEL             1226
#define IDC_SCREENSHOTSAVINGPARAMS      1227
#define IDC_MAXTHREADSEDIT              1227
#define IDC_ALWAYSCOPYTOCLIPBOARD       1228
#define IDC_RESULTSPLACEHOLDER          1229
#define IDC_COLORSGROUP                 1230
#define IDC_HISTORYTREE                 1232
#define IDC_TIMEPERIODLABEL             1233
#define IDC_MONTHCOMBO                  1234
#define IDC_DOWNLOADTHUMBS              1235
#define IDC_SESSIONSCOUNTLABEL          1237
#define IDC_FILESCOUNTLABEL             1238
#define IDC_SESSIONSCOUNTDESCR          1239
#define IDC_FILESCOUNTDESCR             1240
#define IDC_EDITTHUMBNAILPRESET         1241
#define IDC_THUMBSCOMBO                 1242
#define IDC_THUMBSCOMBOLABEL            1243
#define IDC_COMBOPREVIEW                1244
#define IDC_UPLOADTRAFFICDESCR          1245
#define IDC_UPLOADTRAFFICLABEL          1246
#define IDC_FRAMEWIDTHLABEL             1250
#define IDC_THUMBTEXTCHECKBOX           1252
#define IDC_DESCRIPTIONLABEL            1253
#define IDC_VALUEEDIT                   1254
#define IDC_RESIZEPRESETSBUTTON         1255
#define IDC_EDITPROFILE                 1256
#define IDC_PROFILETOOBLARPLACEBUTTON   1257
#define IDC_RESIZEPRESETSBUTTON2        1257
#define IDC_SHORTENINGURLSERVERBUTTON   1257
#define IDC_RESIZEMODECOMBO             1258
#define IDC_SMARTCONVERTING             1259
#define IDC_PROFILECOMBO                1260
#define IDC_WIDTHRADIO                  1262
#define IDC_BUTTON1                     1263
#define IDC_THUMBBACKGROUND             1263
#define IDC_ADDITEM                     1263
#define IDC_BROWSESCRIPTBUTTON          1263
#define IDC_CLEARLOGBUTTON              1263
#define IDC_CLEARHISTORYBTN             1263
#define IDC_THUMBBACKGROUNDLABEL        1264
#define IDC_DELETEITEM                  1264
#define IDC_GOOGLECODELINK              1265
#define IDC_UPBUTTON                    1265
#define IDC_CURRENTPROFILELABEL         1266
#define IDC_DOWNBUTTON                  1266
#define IDC_RESIZEMODELABEL             1267
#define IDC_PROFILELABEL                1268
#define IDC_REMOVEBACKGROUND            1269
#define IDC_AEROONLY                    1270
#define IDC_IMAGE                       1271
#define IDC_CHECK1                      1272
#define IDC_AUTOSTARTUP                 1272
#define IDC_PRESERVE_EXIF               1272
#define IDC_PASTEHTMLONCTRLVCHECKBOX    1272
#define IDC_SHORTENURLFROMTRAYCHECKBOX  1272
#define IDC_ADDFILEPROTOCOL             1272
#define IDC_REMEMBERIMAGESERVERSETTINGS 1272
#define IDC_OPENSCREENSHOTINEDITORCHECKBOX 1272
#define IDC_DROPVIDEOFILESTOTHELIST     1272
#define IDC_SHORTENLINKSCHECKBOX        1272
#define IDC_EXECUTESCRIPTCHECKBOX       1272
#define IDC_VIDEOENGINECOMBO            1273
#define IDC_CHECK5                      1273
#define IDC_REMEMBERFILESERVERSETTINGS  1273
#define IDC_ALLOWALTTABINIMAGEEDITOR    1273
#define IDC_FOUNDABUG                   1274
#define IDC_RESULTSLABEL                1274
#define IDC_OUTPUTTEXT                  1275
#define IDC_COPYTOCLIPBOARD             1276
#define IDC_PASTEHTML                   1277
#define IDC_INPUTTEXT                   1278
#define IDC_SERVENAMELABEL              1279
#define IDC_SOURCEURLLABEL              1281
#define IDC_DESCRIPTION                 1282
#define IDC_VIDEOSNAPSHOTSFOLDERBUTTON  1283
#define IDC_VIDEOSNAPSHOTSFOLDERLABEL   1284
#define IDC_SNAPSHOTFILENAMELABEL       1285
#define IDC_OPENFOLDER                  1286
#define IDC_RESULTSEDIT                 1287
#define IDC_SHORTENURLTIP               1288
#define IDC_SERVERCOMBOBOX              1289
#define IDC_CONNECTIONNAMELABEL         1290
#define IDC_SERVERSTATIC                1291
#define IDC_AUTHENTICATIONLABEL         1292
#define IDC_REMOTEDIRECTORYLABEL        1293
#define IDC_DOWNLOADURLLABEL            1294
#define IDC_THEURLOFUPLOADEDLABEL       1295
#define IDC_URLLABEL                    1296
#define IDC_EXAMPLEURLLABEL             1296
#define IDC_DIRECTORYEDIT               1297
#define IDC_DIRECTORYLABEL              1298
#define IDC_PRESETSBUTTON               1299
#define IDC_SERVERLABEL                 1300
#define IDC_CONTEXTMENUITEMSLABEL       1300
#define IDC_FTPSETTINGSBUTTON           1301
#define IDC_IMAGESERVERPLACEHOLDER      1301
#define IDC_DOAUTHCHECKBOX              1302
#define IDC_FILESERVERPLACEHOLDER       1302
#define IDC_MENUITEMLABEL               1302
#define IDC_AUTOSTARTUPCHECKBOX         1303
#define IDC_FILESERVERPLACEHOLDER2      1303
#define IDC_TRAYSERVERPLACEHOLDER       1303
#define IDC_DELETEACCOUNTLABEL          1303
#define IDC_CAPTUREPRINTSCREENCHECKBOX  1304
#define IDC_CONTEXTMENUSERVERPLACEHOLDER 1304
#define IDC_DOLOGINLABEL                1304
#define IDC_EXPLORERINTEGRATION         1305
#define IDC_URLSHORTENERPLACEHOLDER     1305
#define IDC_PARAMETERSLABEL             1305
#define IDC_DOLOGINLABEL2               1305
#define IDC_SIGNUPLINK                  1305
#define IDC_ACCOUNTINFO                 1306
#define IDC_AUTHORLABEL                 1306
#define IDC_EDIT                        1307
#define IDC_WEBSITELABEL                1307
#define IDC_SERVERGROUPBOX              1308
#define IDC_TOOLBARPLACEHOLDER          1308
#define IDC_USERICON                    1309
#define IDC_FONTCOMBO                   1309
#define IDC_FOLDERICON                  1310
#define IDC_SAVE                        1310
#define IDC_FOLDERLABEL                 1311
#define IDC_SCRIPTFILENAMEEDIT          1311
#define IDC_IMAGEPROCESSINGPARAMS       1312
#define IDC_SAVESTATUSLABEL             1312
#define IDC_SETTINGSBUTTONPLACEHOLDER   1313
#define IDC_SERVERPLACEHOLDER           1313
#define IDC_SETTINGSBUTTONPLACEHOLDER2  1314
#define IDC_AUTHORNAMELABEL             1314
#define IDC_DEFAULTSETTINGSCHECKBOX     1315
#define IDC_RADIO3                      1315
#define IDC_CURRENTMONTHRADIO           1315
#define IDC_PROCESSIMAGESCHECKBOX       1316
#define IDC_STATUSLABEL                 1316
#define IDC_DEFAULTTHUMBSETTINGSCHECKBOX 1317
#define IDC_THUMBTEMPLATECOMBOLABEL     1318
#define IDC_THUMBTEMPLATECOMBO          1319
#define IDC_THUMBRESIZELABEL            1320
#define IDC_WIDTHEDITUNITS              1321
#define IDC_THUMBRESIZECOMBO            1322
#define IDOK2                           1323
#define IDC_BROWSESERVERFOLDERS         1324
#define IDR_bottomLeftShadow            15001
#define IDR_bottomRightShadow           15002
#define IDR_bottomShadow                15003
#define IDR_leftShadow                  15004
#define IDR_rightShadow                 15005
#define IDR_topLeftShadow               15006
#define IDR_topRightShadow              15007
#define IDR_topShadow                   15008
#define IDR_topLeftShadowSquare         15009
#define IDR_topRightShadowSquare        15010
#define ID_VIEW_DELETE                  32775
#define ID_VIEW                         32776
#define ID_DELETE                       32777
#define IDM_VIEW                        32778
#define IDM_DELETE                      32779
#define ID_PROPERTIES                   32780
#define ID_VIEW_VIEW                    32781
#define ID_0_32782                      32782
#define ID_0_EDIT                       32783
#define IDM_EDIT                        32784
#define ID_0_32785                      32785
#define ID_0_32786                      32786
#define ID_0_32787                      32787
#define IDC_PASTE                       32788
#define ID_0_32789                      32789
#define IDM_ADDFOLDER                   32790
#define IC_DELETEALL                    32791
#define IDC_DELETEALL                   32792
#define ID_0_OPENINOLDER                32793
#define ID_0_OPENFINOLDER               32794
#define IDM_OPENFINOLDER                32795
#define IDM_OPENINFOLDER                32796
#define ID_Menu                         32797
#define IDM_ADDFILES                    32798
#define ID_Menu32799                    32799
#define ID_0_32800                      32800
#define IDM_COPYFILETOCLIPBOARD         32801
#define IDM_SAVEAS                      32802
#define ID_0_SAVEAS                     32802
#define ID_0_EDITINEXTERNALEDITOR       32803
#define IDM_EDITINEXTERNALEDITOR        32804
#define ID_Menu32805                    32805
#define ID__DATA                        32806
#define ID__DATA32807                   32807
#define ID_0_                           32808
#define IDM_COPYFILEPATH                32809
#define ID_0_EXTRACTFRAMES              32810
#define IDM_EXTRACTFRAMES               32811
#define ID_Menu32812                    32812
#define IDM_OPENINDEFAULTVIEWER         32813

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        309
#define _APS_NEXT_COMMAND_VALUE         32814
#define _APS_NEXT_CONTROL_VALUE         1317
#define _APS_NEXT_SYMED_VALUE           128
#endif
#endif
