// This file was generated by WTL subclass control wizard 
// TabListBox.cpp : Implementation of CTabListBox

#include "stdafx.h"
#include "TabListBox.h"

// CTabListBox
CTabListBox::CTabListBox()
{
}

CTabListBox::~CTabListBox()
{
}

LRESULT CTabListBox::OnDrawitem(UINT uMsg, WPARAM wParam, LPARAM lParam, BOOL& bHandled)
{
	LPDRAWITEMSTRUCT lpdis = (LPDRAWITEMSTRUCT) lParam;
	int iItemIndex = lpdis->itemID;
	CDC dc = lpdis->hDC;
	TCHAR buf[256]=_T("");
	GetText(iItemIndex, buf);
	dc.SetBkMode(TRANSPARENT);
	if(lpdis->itemState & ODS_SELECTED )
	{
		CRect roundedRect(lpdis->rcItem);
		roundedRect.DeflateRect(3,3);
		CPen pen;
		pen.CreatePen(PS_SOLID, 1, 0xC5C5C5);
		dc.SelectPen(pen);
		dc.RoundRect(roundedRect, CPoint(2,2));
		CRect rc(lpdis->rcItem);
		rc.DeflateRect(4,4);

		TRIVERTEX vertex[2] = { {rc.left, rc.top, 0xF500, 0xF200, 0xE200, 0x0000},   
								{rc.right, rc.bottom, 0xEF00, 0xD000, 0x7700, 0x0000}};
		GRADIENT_RECT gradientrc = {0, 1};
		dc.GradientFill(vertex, 2, &gradientrc, 1, GRADIENT_FILL_RECT_V);
	}
	else
	{
		CBrush br;
		br.CreateSolidBrush(GetSysColor(COLOR_WINDOW));
		dc.FillRect(&lpdis->rcItem,br);
	}

	DrawText(dc, buf, lstrlen(buf), &lpdis->rcItem,	DT_CENTER|DT_VCENTER|DT_SINGLELINE	);
	dc.Detach();
	return 0;
}

LRESULT CTabListBox::OnMeasureItem(UINT uMsg, WPARAM wParam, LPARAM lParam, BOOL& bHandled)
{
	LPMEASUREITEMSTRUCT lpmis = (LPMEASUREITEMSTRUCT) lParam;
	lpmis->itemHeight = 34;
	bHandled = true;
	return TRUE;
}


